# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lista_compras.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from functools import partial
import mysql.connector
from PyQt5.QtWidgets import QMainWindow
import tela_id_etiqueta
import tela_id_etiqueta_retirar
import tela_inf_prod
import alerta_prod_venc
import re
import datetime

con = mysql.connector.connect(host='localhost',database='db_ProdutosTCC',user='root',password='lele77608')
cursor = con.cursor()


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        self.produtos = []
        self.produtos_na_lista = []
        self.epcs_na_lista = []
        self.preco_total = 0

        #self.tela_id_etiqueta_Window = QtWidgets.QMainWindow()
        #self.tela_id_etiqueta_ui = tela_id_etiqueta.Ui_MainWindow()
        #self.tela_id_etiqueta_ui.setupUi(self.tela_id_etiqueta_Window)

        #self.tela_id_etiqueta_retirar_Window = QtWidgets.QMainWindow()
        #self.tela_id_etiqueta_retirar_ui = tela_id_etiqueta_retirar.Ui_MainWindow()
        #self.tela_id_etiqueta_retirar_ui.setupUi(self.tela_id_etiqueta_retirar_Window)

        self.tela_inf_prod_Window = QtWidgets.QMainWindow()
        self.tela_inf_prod_ui = tela_inf_prod.Ui_MainWindow()
        self.tela_inf_prod_ui.setupUi(self.tela_inf_prod_Window)

        self.alerta_prod_venc_Window = QtWidgets.QMainWindow()
        self.alerta_prod_venc_ui = alerta_prod_venc.Ui_MainWindow()
        self.alerta_prod_venc_ui.setupUi(self.alerta_prod_venc_Window)

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setVerticalSpacing(40)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.valortotal = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(12)
        self.valortotal.setFont(font)
        self.valortotal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.valortotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valortotal.setObjectName("valortotal")
        self.gridLayout_2.addWidget(self.valortotal, 3, 3, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1101, 456))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(-1, 0, -1, 350)
        self.gridLayout.setObjectName("gridLayout")

        #self.inserir_item = QtWidgets.QPushButton(self.centralwidget)
        #font = QtGui.QFont()
        #font.setPointSize(12)
        #self.inserir_item.setFont(font)
        #self.inserir_item.setCheckable(True)
        #self.inserir_item.setAutoExclusive(True)
        #self.inserir_item.setStyleSheet("QPushButton:pressed { background-color: none; }")
        #self.inserir_item.setObjectName("inserir_item")
        #self.gridLayout_2.addWidget(self.inserir_item, 5, 0, 3, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 4)
        self.maisdetalhes = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)

        self.localizar_item = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.localizar_item.setFont(font)
        self.localizar_item.setCheckable(True)
        self.localizar_item.setAutoExclusive(True)
        self.localizar_item.setStyleSheet("QPushButton:pressed { background-color: none; }")
        self.localizar_item.setObjectName("localizar_item")
        self.gridLayout_2.addWidget(self.localizar_item, 5, 3, 3, 1)

        self.pagar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pagar.setFont(font)
        self.pagar.setCheckable(True)
        self.pagar.setAutoExclusive(True)
        self.pagar.setObjectName("Finalizar Compra")
        self.gridLayout_2.addWidget(self.pagar, 5, 1, 3, 1)

        #self.remover_item = QtWidgets.QPushButton(self.centralwidget)
        #font = QtGui.QFont()
        #font.setPointSize(12)
        #self.remover_item.setFont(font)
        #self.remover_item.setCheckable(True)
        #self.remover_item.setAutoExclusive(True)
        #self.remover_item.setObjectName("Remover Item")
        #self.gridLayout_2.addWidget(self.remover_item, 5, 2, 3, 1)

        self.maisdetalhes.setFont(font)
        self.maisdetalhes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.maisdetalhes.setAlignment(QtCore.Qt.AlignCenter)
        self.maisdetalhes.setObjectName("maisdetalhes")
        self.gridLayout_2.addWidget(self.maisdetalhes, 0, 3, 1, 1)
        self.produto = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.produto.setFont(font)
        self.produto.setObjectName("produto")
        self.gridLayout_2.addWidget(self.produto, 0, 0, 1, 1)
        self.quantidade = QtWidgets.QLabel(self.centralwidget)
        self.quantidade.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quantidade.setFont(font)
        self.quantidade.setObjectName("quantidade")
        self.gridLayout_2.addWidget(self.quantidade, 0, 1, 1, 1)
        self.preco = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.preco.setFont(font)
        self.preco.setAlignment(QtCore.Qt.AlignCenter)
        self.preco.setObjectName("preco")
        self.gridLayout_2.addWidget(self.preco, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def atualizar_preco(self):
        self.precos = []
        for i in self.produtos_na_lista:
            preco_item = i[1]
            self.precos.append(preco_item)
        preco_total = round(sum(self.precos), 2)
        self.preco_total = preco_total
        _translate = QtCore.QCoreApplication.translate
        self.valortotal.setText(_translate("MainWindow", "Total da compra: R$ {}                               ").format(preco_total))

    def criar_linha(self, MainWindow, i=int, id_etiqueta=str):

        consulta_nome = """SELECT Nome FROM tbl_Produtos WHERE ID_RFID = '{}'""".format(id_etiqueta)
        consulta_preco = """SELECT Preco FROM tbl_Produtos WHERE ID_RFID = '{}'""".format(id_etiqueta)
        consulta_id = """SELECT ID_Produto FROM tbl_Produtos WHERE ID_RFID = '{}'""".format(id_etiqueta)
        consulta_data = """SELECT Data_Validade FROM tbl_Produtos WHERE ID_RFID = '{}'""".format(id_etiqueta)
        consulta_marca = """SELECT Marca FROM tbl_Produtos WHERE ID_RFID = '{}'""".format(id_etiqueta)

        cursor.execute(consulta_nome)
        resultado_nome = cursor.fetchall()[0][0]
        #cursor.reset()

        cursor.execute(consulta_preco)
        resultado_preco = cursor.fetchall()
        #cursor.reset()

        cursor.execute(consulta_id)
        resultado_id = cursor.fetchall()
        #cursor.reset()

        cursor.execute(consulta_data)
        resultado_data = cursor.fetchall()[0][0]
        #cursor.reset()

        cursor.execute(consulta_marca)
        resultado_marca = cursor.fetchall()[0][0]
        #cursor.reset()

        id = str(resultado_id[0][0])

        _translate = QtCore.QCoreApplication.translate
        nome_item=resultado_nome
        self.nome_item = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nome_item.setFont(font)
        self.gridLayout.addWidget(self.nome_item, i, 0, 1, 1)
        setattr(self, f'nome{id}', self.nome_item)
        self.nome_item.setObjectName('nome'+id)
        self.nome_item.setText(_translate("MainWindow", nome_item+' '+resultado_marca))

        qtde_item="qtde"+id
        self.qtde_item = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qtde_item.setFont(font)
        self.gridLayout.addWidget(self.qtde_item, i, 1, 1, 1)
        self.qtde_item.setAlignment(QtCore.Qt.AlignCenter)
        setattr(self, f'qtde{id}', self.qtde_item)
        self.qtde_item.setObjectName(qtde_item)
        self.qtde_item.setText(_translate("MainWindow", "1"))

        preco_item=resultado_preco[0][0]
        self.preco_item = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.preco_item.setFont(font)
        self.gridLayout.addWidget(self.preco_item, i, 2, 1, 1)
        setattr(self, f'preco{id}', self.preco_item)
        self.preco_item.setObjectName('preco'+id)
        self.preco_item.setText(_translate("MainWindow", "R$ " + str(preco_item)))

        saiba_mais='saiba_mais'
        self.saiba_mais = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saiba_mais.setFont(font)
        self.gridLayout.addWidget(self.saiba_mais, i, 3, 1, 1)
        self.saiba_mais.setCheckable(True)
        self.saiba_mais.setAutoExclusive(True)
        setattr(self, f'saiba_mais{id}', self.saiba_mais)
        self.saiba_mais.setObjectName(saiba_mais+id)
        self.saiba_mais.setText(_translate("MainWindow", "saiba mais"))

        self.produtos.clear()
        self.produtos.append(id)
        self.produtos.append(preco_item)
        self.produtos.append(resultado_data)
        aux = []
        aux.append(id)
        aux.append(preco_item)
        aux.append(resultado_data)
        self.produtos_na_lista.append(aux)

        nome_botao = str(self.saiba_mais.objectName())

        self.atualizar_preco()

        dia_de_hoje = datetime.date.today()
        dia_de_hoje_br = dia_de_hoje.strftime("%d/%m/%Y")

        date_format = "%d/%m/%Y"

        if resultado_data != 'N/A':
            date_hoje = datetime.datetime.strptime(dia_de_hoje_br, date_format).date()
            date_produto = datetime.datetime.strptime(resultado_data, date_format).date()

            if date_produto < date_hoje:
                self.alerta_prod_venc_ui.res_prod_venc_prod.setText(_translate("MainWindow", "{}").format(nome_item))
                self.alerta_prod_venc_ui.res_prod_venc_marca.setText(_translate("MainWindow", "{}").format(resultado_marca))
                self.alerta_prod_venc_ui.res_prod_venc_data.setText(_translate("MainWindow", "{}").format(resultado_data))
                self.nome_item.setStyleSheet("color: rgb(255, 0, 0);")
                self.qtde_item.setStyleSheet("color: rgb(255, 0, 0);")
                self.preco_item.setStyleSheet("color: rgb(255, 0, 0);")
                self.show_tela_alerta_prod_venc()

            self.alerta_prod_venc_ui.prod_venc_ok.clicked.connect(self.alerta_prod_venc_Window.close)

        self.saiba_mais.clicked.connect(lambda: self.show_tela_inf_prod(nome_botao))
        self.tela_inf_prod_ui.pushButton.clicked.connect(self.tela_inf_prod_Window.close)

    def show_tela_inf_prod(self, nome_botao):

        id = int(re.sub(r'[^0-9]', '', nome_botao))

        consulta_banco = """SELECT Nome, Marca, Tipo, Data_validade, Lote, Loc_corredor, Loc_Secao, Qnt_Estoque, Preco, Descricao_Nutricional, 
                         Alergicos FROM tbl_Produtos WHERE ID_Produto = '{}'""".format(id)

        cursor.execute(consulta_banco)
        resultado_geral = cursor.fetchall()

        resultado_Nome = resultado_geral[0][0]
        resultado_Marca = resultado_geral[0][1]
        resultado_Tipo = resultado_geral[0][2]
        resultado_Data_validade = resultado_geral[0][3]
        resultado_Lote = resultado_geral[0][4]
        resultado_Loc_Corredor = resultado_geral[0][5]
        resultado_Loc_Secao = resultado_geral[0][6]
        resultado_Qtd_Estoque = resultado_geral[0][7]
        resultado_Preco = resultado_geral[0][8]
        resultado_Descricao_Nutricional = resultado_geral[0][9]
        resultado_Alergicos = resultado_geral[0][10]

        #cursor.reset()

        _translate = QtCore.QCoreApplication.translate
        self.tela_inf_prod_ui.res_nome.setText(_translate("MainWindow", "{}").format(resultado_Nome))
        self.tela_inf_prod_ui.res_marca.setText(_translate("MainWindow", "{}").format(resultado_Marca))
        self.tela_inf_prod_ui.res_tipo.setText(_translate("MainWindow", "{}").format(resultado_Tipo))
        self.tela_inf_prod_ui.res_data.setText(_translate("MainWindow", "{}").format(resultado_Data_validade))
        self.tela_inf_prod_ui.res_lote.setText(_translate("MainWindow", "{}").format(resultado_Lote))
        self.tela_inf_prod_ui.res_loccorr.setText(_translate("MainWindow", "{}").format(resultado_Loc_Corredor))
        self.tela_inf_prod_ui.res_locsec.setText(_translate("MainWindow", "{}").format(resultado_Loc_Secao))
        self.tela_inf_prod_ui.res_estoque.setText(_translate("MainWindow", "{}").format(resultado_Qtd_Estoque))
        self.tela_inf_prod_ui.res_preco.setText(_translate("MainWindow", "R${}").format(resultado_Preco))
        self.tela_inf_prod_ui.res_desc.setText(_translate("MainWindow", "{}").format(resultado_Descricao_Nutricional))
        self.tela_inf_prod_ui.res_alergicos.setText(_translate("MainWindow", "{}").format(resultado_Alergicos))

        self.show_tela_inf_prod_max()

    def show_tela_alerta_prod_venc(self):
        self.alerta_prod_venc_Window.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
        self.alerta_prod_venc_Window.setWindowState(Qt.WindowFullScreen)
        self.alerta_prod_venc_Window.show()

    def show_tela_inf_prod_max(self):
        self.tela_inf_prod_Window.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
        self.tela_inf_prod_Window.setWindowState(Qt.WindowFullScreen)
        self.tela_inf_prod_Window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.valortotal.setText(_translate("MainWindow", "Total da compra: R$ 0,00                               "))
        #self.inserir_item.setText(_translate("MainWindow", "inserir item"))
        self.maisdetalhes.setText(_translate("MainWindow", "Mais detalhes"))
        self.produto.setText(_translate("MainWindow", "Produto"))
        self.quantidade.setText(_translate("MainWindow", "Quantidade"))
        self.preco.setText(_translate("MainWindow", "Preço"))
        self.pagar.setText(_translate("MainWindow", "Finalizar Compra"))
        #self.remover_item.setText(_translate("MainWindow", "Remover Item"))
        self.localizar_item.setText(_translate("MainWindow", "Localizar Item"))
