# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapa_do_mercado.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(856, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fundo_branco = QtWidgets.QLabel(self.centralwidget)
        self.fundo_branco.setGeometry(QtCore.QRect(-270, -200, 1741, 1011))
        self.fundo_branco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fundo_branco.setText("")
        self.fundo_branco.setObjectName("fundo_branco")
        self.mapa_mercado = QtWidgets.QLabel(self.centralwidget)
        self.mapa_mercado.setGeometry(QtCore.QRect(20, 50, 821, 391))
        self.mapa_mercado.setStyleSheet("background-image: url(:/newPrefix/mapa_mercado.png);")
        self.mapa_mercado.setText("")
        self.mapa_mercado.setPixmap(QtGui.QPixmap(":/newPrefix/mapa_mercado.png"))
        self.mapa_mercado.setScaledContents(True)
        self.mapa_mercado.setObjectName("mapa_mercado")
        self.indicador = QtWidgets.QLabel(self.centralwidget)
        self.indicador.setGeometry(QtCore.QRect(90, 160, 10, 51))
        self.indicador.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.indicador.setText("")
        self.indicador.setObjectName("indicador")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(680, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("color: rgb(0, 0, 255);")
        self.botao_voltar.setObjectName("botao_voltar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 856, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botao_voltar.setText(_translate("MainWindow", "Voltar"))
import imagens_rc
